### ISSUE TITLE
when you zoom in too much, the streets disappear

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#119]
Go to the worldcup and select (for instance) the Netherlands,
select North Holland,
select Beverwijk
zoom in.
At a certain point you still see everything: The litter and the streets.
If you zoom in a little more, the litter is still visible, but the streets are not shown anymore.
![Schermafdruk 2020-10-19_21 05 03 (irfanview)](https://user-images.githubusercontent.com/2518047/103152766-56f73580-478b-11eb-96bd-7be0d09a8495.jpg)
![Schermafdruk 2020-10-19_21 05 07 (irfanview)](https://user-images.githubusercontent.com/2518047/103152768-58286280-478b-11eb-8b55-75ea59ad3d30.jpg)

**Comment by xlcrr** [comment]
I don't think there is much we can do about this. It's related to OSM
