### ISSUE TITLE
Website, not all options can be reached with TAB-key.

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#121]
go to homepage, openlittermap.com
use 'TAB' to 'scroll' through the page.
You will see that it is not possible to reach all fields (to do everything without a mouse).
For instance in the top menu, the option 'More' can not be reached.

**Comment by xlcrr** [comment]
Tab is jumping between a-tags not p-tags. Closing the issue as its on Trello
