### ISSUE TITLE
Last-Activity not shown on Team-page

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#130]
See printscreen.

I am the only member in this team, so this is my data,
however, i am missing the data in the last column, where the last-activity should have been shown.

(maybe something to fix together with issue https://github.com/OpenLitterMap/openlittermap-web/issues/126)

![Schermafdruk 2020-12-30_17 27 21 (irfanview)](https://user-images.githubusercontent.com/2518047/103367129-95ab2980-4ac4-11eb-9578-485ceb2b2d0c.jpg)

**Comment by GeniJaho** [comment]
@xlcrr this one has been fixed and is working in production, the issue was that the pivot table updated_at was not being updated. Closing this.
