### ISSUE TITLE
Submit after tagging a photo results in going back to the first picture, instead of going to the next picture

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#141]
I am tagging a batch of pictures,
the screen displays the numbers of the different pictures and i tag a pictures somewhere in the middle.
After pressing 'Submit', i expect the next picture to appear,
In reality picture number 1 is shown (which i intentionally skipped)
![Schermafdruk 2021-01-18_20 16 42 (irfanview)](https://user-images.githubusercontent.com/2518047/104955294-4a50b080-59ca-11eb-8836-747573cb195e.jpg)
![Schermafdruk 2021-01-18_20 16 47 (irfanview)](https://user-images.githubusercontent.com/2518047/104955297-4ae94700-59ca-11eb-8959-17cb302ef61f.jpg)

**Comment by xlcrr** [comment]
Fixed https://github.com/OpenLitterMap/openlittermap-web/commit/751a1d2aff651f389542050ff0eb5ccd10206d0c
