### ISSUE TITLE
LitterWorldCup, after scrolling down and clicking on a country, the next page doesn't start at the top

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#144]
If you go to the 'World Cup' and you scroll down to one of the countries,
The page with that country opens,
However, it does not start at the top, but it seems to start where you were in the previous screen.
For instance if you scroll down to the netherlands, and click on it,
The next page opens at 5th place.
![Schermafdruk 2021-01-18_23 00 31 (irfanview)](https://user-images.githubusercontent.com/2518047/104966439-2c427a80-59e1-11eb-8a6a-757ef8946ebb.jpg)
![Schermafdruk 2021-01-18_23 00 38 (irfanview)](https://user-images.githubusercontent.com/2518047/104966443-2d73a780-59e1-11eb-8c45-b9faa917c4d8.jpg)

**Comment by xlcrr** [comment]
Fixed by https://github.com/OpenLitterMap/openlittermap-web/pull/280
