### ISSUE TITLE
Creator of picture not shown on Global map (while it is shown on the WorldCup)

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#146]
see printscreens,

i am the creator of the cans in this area.
Go to the worldcup and zoom in, the creator of the picture is not mentioned.
Go to the global map and zoom in, the creator is mentioned.
![Schermafdruk 2021-01-18_23 11 36 (irfanview) - Copy](https://user-images.githubusercontent.com/2518047/104967471-b855a180-59e3-11eb-882f-2cdebad36181.jpg)
![Uploading Schermafdruk 2021-01-18_23.14.27 (irfanview) - Copy.jpg…]()

**Comment by xlcrr** [comment]
I think this has been fixed
