### ISSUE TITLE
Improvement: enlarge picture on click so tagging becomes easier

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#151]
See screenprint,
I am tagging a lot of pictures and now i have to see what is in the picture,
or for instance a picture with 40-50 sigarettebutts on it.

It would help a lot if it was possible to just click on the picture once, so that the picture enlarges, to be able to see what is on it (or to see the brand of the bottle etc).
After clicking again, the normal state would be present again.
(what i do now, is saving the picture and opening/enlarge it, this is very timeconsuming).
![Schermafdruk 2021-01-21_10 01 17 (irfanview)](https://user-images.githubusercontent.com/2518047/105327791-a0db0c00-5bcf-11eb-8428-d5c7630a8a06.jpg)

**Comment by GeniJaho** [comment]
We fixed this issue about a month ago. Closing it.
