### ISSUE TITLE
Important improvement on the Global Map

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#153]
![Schermafdruk 2021-01-23_11 59 36 (irfanview)](https://user-images.githubusercontent.com/2518047/105577218-65c80c80-5d78-11eb-815e-0225100f73c5.jpg)
A very important feature is missing,
And i think it would be rather easy to start with a 'minimum viable product' and to improve from there.

What we are doing, is creating a lot of data that is combined in the database, for others to download,
However, what most litter-pickers do, is talk about the litter that they picked themselves. 
What they picked today, or last week, or this january compare to last year etc.

Most of them do that with a map.
For instance, this is a map of what i did while running and picking litter in 1 trip and these are the  screenprints that i use for social media or for a webinar etc.
(see screenprint)

The Global Map is perfect for that and it already shows what we need, but at this moment it is not possible to only show your own data, it just shows all data, of all people.
so we can not create a screenprint of what 'I' did during a specific event.

So here are some things that would help a lot (in order of importance):
- create the opportunity to filter between your own data or all data.

Next:
- create filters with which you can declare what date/time you want to see (from date/time - to date/time)

Next:
- create filters with which you can declare what kind of data you want to see (all cans and/or McDonalds etc).

**Comment by xlcrr** [comment]
Giving each user their own profile, with their own data is on the todo list

**Comment by xlcrr** [comment]
I don't think we will put the users data on the global map. But we can give them their own map

**Comment by xlcrr** [comment]
This is done
