### ISSUE TITLE
Profile-page, 'this week' shows pictures that were not taken this week, (but uploaded this week?)

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#158]
see screenprint,
if you choose 'this week', the map shows pictures.
However, it also shows litter in a part of the Netherlands where i have not been in last week, 
so i think it is not showing 'date-picture-taken' but 'data-picture-uploaded',
which could make sense, because i am uploading old pictures.

I would expect to see only the pictures that were really taken in the period that is chosen.
![Schermafdruk 2021-01-24_19 00 11 (irfanview)](https://user-images.githubusercontent.com/2518047/105639282-96db3680-5e77-11eb-8eaa-04622da66b3a.jpg)

**Comment by GeniJaho** [comment]
@FredMark I think this one is already solved. On the profile page, there is a calendar that also allows you to choose between Uploaded and Taken dates.

![image](https://user-images.githubusercontent.com/29065651/125818113-fb8fe9a1-62d5-46ec-95d2-34bbcd138374.png)

**Comment by FredMark** [comment]
@GeniJaho 
Nice,
when i reported it, this functionality was not there yet.
If i choose a large period and let it show the uploaded data, it says some number,
and if i change it to 'picture taken', it shows another number, so it looks like it doing both things.
(Not sure if the number itselfs is right, but i presume yes).
This one can be closed also!
