### ISSUE TITLE
Profile-page, improvement: ability to make the map fullscreen

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#166]
At this moment the map is in the center of the screen.
you are able to zoom in and zoom out.
This is nice!

Improvement:
The ability to click on a button so the map becomes full-screen (and some 'close'-button on it to go back to the normal display).
In that case it is much easier to make screenprints of the map with all your litter to share in powerfull stories.

**Comment by GeniJaho** [comment]
I think this one is already implemented, the button is in the top-right corner of the map.

![image](https://user-images.githubusercontent.com/29065651/125491254-b300fc1f-b2cd-4512-8549-bb88bf1462ec.png)

**Comment by FredMark** [comment]
@GeniJaho 
Cool, never saw that, or it was created after me reporting it.
However, that is exactly what i meant, thanks!
(No pictures are being shown at this moment, but i guess that is another issue, opening the map fullscreen is possible).
