### ISSUE TITLE
About-page, left-aligned or right-aligned

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#170]
See printscreen.

All text is left-aligned, except for this piece of text?
![Schermafdruk 2021-01-24_21 26 18 (irfanview)](https://user-images.githubusercontent.com/2518047/105642623-1aeae980-5e8b-11eb-827b-643f27cdaf4d.jpg)

**Comment by GeniJaho** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/29065651/125446858-767024ea-d415-491a-b3c5-a176fc7eb598.png)

**Comment by xlcrr** [comment]
This was a feature, not a bug
