### ISSUE TITLE
Settings-page, Not possible to "Change Personal Details" (1 of them) if you don't change all of them

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#177]
I created my account some time ago and now see that my name is printed at some places.
It says 'default' in those screens, so i looked for the setting and indeed see that under
More > Settings > Personal Settings,
there is a field 'name' that is filled with 'default' instead of a name.

I change this value to a real name and press "Update Details".
Now the error appears:
- Unique Identifier The username has already been taken.
- Email The email has already been taken.

This makes it impossible to change just one setting.

**Comment by GeniJaho** [comment]
@FredMark This one is also fixed. You can change your personal details one by one.

**Comment by FredMark** [comment]
@GeniJaho 
Yes, cool.
This was not possible first, but it is now,
i noticed while looking at the settings of my name (and changing it) because 'default' was shown as my name.
This one is solved also and can be closed, thanks!
