### ISSUE TITLE
Pictures disappear from the global map when you zoom in

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#182]
yesterday i took a picture of a can and uploaded it.
I wanted to created a twitter-post of it, so i looked for it in the Profile-
![Schermafdruk 2021-01-29_13 44 56 (irfanview)](https://user-images.githubusercontent.com/2518047/106276724-44fc2d00-6238-11eb-8728-0aaa6c864b06.jpg)
![Schermafdruk 2021-01-29_13 45 01 (irfanview)](https://user-images.githubusercontent.com/2518047/106276730-462d5a00-6238-11eb-98e3-86333c562f41.jpg)

page (which is a good way, because that will show you your own data, so no interference with other people's pictures.
However, since the tags are not shown upon the picture, i decided to use the Global map after all.

Bug:
If you are not yet completely zoomed-in, i see a green circle with a '2' in it,
if i zoom in closer to get to the picture itself, it disappears?
See screenprint

**Comment by xlcrr** [comment]
Not much we can do about this, will need to dig deep into the clusters package which is not on the todo list anytime soon
