### ISSUE TITLE
Global Map, when it is opened, it should be shown zoomed in more

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#186]
When you go to the Global Map, the entire world is shown, but it is zoomed out too much,
so you see countries more than once.
That is not really a problem, but it also shows a lot of space without litter 
![Schermafdruk 2021-01-31_12 15 20 (irfanview)](https://user-images.githubusercontent.com/2518047/106382272-c251aa00-63be-11eb-860b-72ce5b9f5c4d.jpg)
![Schermafdruk 2021-01-31_12 15 41 (irfanview)](https://user-images.githubusercontent.com/2518047/106382274-c4b40400-63be-11eb-9f36-0602b605fcb1.jpg)

on them.

If you zoom in more (just enough that all items still fit on the page), 
it becomes a much more impressive picture.
see printscreens

**Comment by xlcrr** [comment]
Depends on the monitor I think. Zoomed out works fine for me at the moment

**Comment by xlcrr** [comment]
Closing for now but will keep it in mind
