### ISSUE TITLE
Move the Submit-button to top of 'recently used tags'

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#202]
See printscreen.
I have been tagging a lot of pictures and now tag the pictures that i have skipped in the first time.
However, i also come across some pictures that i thought i had tagged.
If you choose a tag and meant to click 'submit' but choose 'next image' unintentionally, you won't notice this.
So maybe move the 'Submit' button to the top (just above 'Recently used tags') so the top is for submitting, the bottom is for going to previous/next picture.

And if possible, remove as much spaces (horizontal lines of 'empty pixels') 
![Schermafdruk 2021-03-22_22 13 15 (irfanview)](https://user-images.githubusercontent.com/2518047/112059923-cbf4c400-8b5c-11eb-98e1-ad0edd831135.jpg)
because as you can see, if you have a lot of 'recently used tags', you will have to zoom out a lot to still have everything on 1 screen without having to scroll and still be able to see what is on the picture.

**Comment by dassudip2001** [comment]
can i work this issue?

**Comment by xlcrr** [comment]
Hi @dassudip2001 the tagging page needs a complete overhaul, your help would be greatly appreciated! Get in touch with me at info@openlittermap.com for a link to join the slack

**Comment by xlcrr** [comment]
Closing this issue and moving it to trello as part of tags & tagging refactor
