### ISSUE TITLE
Tag Balloon exists twice in same category

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#203]
Probably some quick bugfix while also fixing an issue on several bugs.
As a result, the tag 'Balloon' exists twice in the category 'Other'.
(if you hover over it, both are highlighted)
![Schermafdruk 2021-03-23_12 10 13 (irfanview)](https://user-images.githubusercontent.com/2518047/112137622-c5a02f80-8bd0-11eb-90b2-1f3457b79565.jpg)

**Comment by GeniJaho** [comment]
Couldn't replicate this issue. The Other model has only one entry for Balloons. Is there anything I'm missing?

**Comment by xlcrr** [comment]
This has been fixed, a translation value was duplicated if I remember correctly
