### ISSUE TITLE
Tag 'Brand - Other' should be created

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#204]
At this moment we have a tag 'other' in each category which will help us in the long run.
If users use this tag, we can monitor this and we can decide to create a new tag if this one seems to be missing 
(for instance a lot of users tag pictures with 'other - other' and we notice that a lot of these pictures are in fact 'fireworks'.
In that case we can make this tag and correct these pictures to this newly added tag.

the same goes for Brands.
If users have items with a specific brand which is not in our list, they should be able to use 'brand - other' so we can monitor this as well.
However we don't have this tag.

Solution: Add this new tag (at the bottom of the list) (should also be added for app, but that would be an issue in the app-github).

**Comment by xlcrr** [comment]
This is a good use case for a text input... I think we will include this in the next update

**Comment by xlcrr** [comment]
this can be closed as we added custom tags
