### ISSUE TITLE
Make it impossible to submit a tagged item if only a brand is tagged and not the item itself

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#209]
In order to test something,
i tagged an item with only a brand ('redbull'), but not yet the kind of item ('energycan').
After pressing 'Submit', the picture was submitted, but only with a brand.

If you have not yet given any tag, the submit-button is greyed out,
but i think it would be a wise thing to let it still be greyed out if only a brand is given.
(If you know a brand, you also know what kind of item it is, and submitting a picture without the characteristics of this item should be impossible).

**Comment by xlcrr** [comment]
Sometimes maybe the litter is not identifiable but the brand might be? I don't think we should accept this. Closing the issue so we can reduce open issues but I moved the card to Needs Discussion on trello
