### ISSUE TITLE
Not possible to select a brand near the bottom of the picklist

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#210]
I'm trying to select the brand 'heineken', this is somewhere down the droplist,
if you scroll down (the screen goes up and you are looking at a long brand-list) and click on the tag, 
the top of the screen appears again, but not tag is selected.
Only if you start typing the brand ('hei...', you will see the only option to choose ('heineken') and if you select it, it works.

Looks like it is not possible to choose a brand that is too much 'below' the screen?
![Schermafdruk 2021-04-02_20 37 28 (irfanview)](https://user-images.githubusercontent.com/2518047/113444128-928d4580-93f3-11eb-85ba-9d102d36e74f.jpg)
![Schermafdruk 2021-04-02_20 38 34 (irfanview)](https://user-images.githubusercontent.com/2518047/113444129-9325dc00-93f3-11eb-96f9-b29b144f41f0.jpg)

**Comment by xlcrr** [comment]
This has been fixed
