### ISSUE TITLE
New tags and/or category would be welcome

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#215]
Request via Facebook, (via "Keith Scanlon").

New tag for "NO2 canister" (in Dutch: lachgaspatroon), under a new category like 'narcotics', 

New tag for "jointtube (plastic)", under category 'narcotics',
New tag for "jointtube (paper)", under category 'narcotics',
New tag for "balloon", under category 'narcotics' because in some cases it is clear that these found balloons are the result of a 'laughing gas-party').

**Comment by xlcrr** [comment]
Created new trello board to manage tags

https://trello.com/b/Q7mRVv5w/new-tags-categories
