### ISSUE TITLE
Zooming in on the Profile-Map, does not show the separate items, but only 1 circle with a number

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#218]
If you go to the profile page and look at the map, i see a counter of all items that 'my team' has uploaded,
if i zoom in all the way, it does not show the different items, it keeps showing to icon with the total-number.
![Schermafdruk 2021-04-24_19 15 47 (irfanview)](https://user-images.githubusercontent.com/2518047/115967537-6c128400-a533-11eb-9f9e-3943f48afedb.jpg)

**Comment by xlcrr** [comment]
When you click this, the photos should spiral out in a cluster. We should update the profile map to show the dots when fully zoomed in.

**Comment by xlcrr** [comment]
Fixed by adding supercluster and webGL to teams map
