### ISSUE TITLE
Global Map, not showing that you can click on the dot to see the litter

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#219]
see printscreens, normally if you move around with the mouse and hover above a 'litter-dot', the mouse changes from 'hand' to 'pointer'.
It doesn't anymore, although it is still possible to click on the dot to see the litter.
![Schermafdruk 2021-04-24_15 43 01 (irfanview)](https://user-images.githubusercontent.com/2518047/115967604-df1bfa80-a533-11eb-941c-7475f39bb25c.jpg)
![Schermafdruk 2021-04-24_15 42 55 (irfanview)](https://user-images.githubusercontent.com/2518047/115967606-dfb49100-a533-11eb-87d9-9122ea968a0a.jpg)
![Schermafdruk 2021-04-24_15 42 59 (irfanview)](https://user-images.githubusercontent.com/2518047/115967607-e04d2780-a533-11eb-8545-97f1401cb427.jpg)

**Comment by xlcrr** [comment]
I don't think we are going to be able to add this soon as the leaflet-webGL function is largely outside of our control
