### ISSUE TITLE
Improve size of websockets notification on mobile

### ISSUE THREAD

**Issue by xlcrr** [OpenLitterMap/openlittermap-web#36]
When user sign up or add photos, live events are broadcasted to anyone viewing openlittermap.com/global

However, both desktop + mobile views could be improved ( some ui, css )

In particular, the mobile ui needs a redesign

We will probably incorporate this into #31

**Comment by GeniJaho** [comment]
Has this been resolved? Issue #31 has been merged but not sure if this one has been addressed. Currently the notifications look like this 
![image](https://user-images.githubusercontent.com/29065651/121007804-85ddf280-c792-11eb-84e6-f832f253d906.png)
