### ISSUE TITLE
Password reset could reveal account email addresses

### ISSUE THREAD

**Issue by DarkNormal** [OpenLitterMap/openlittermap-web#371]
Current password reset functionality could expose valid email addresses for accounts on OpenLitterMap

<img width="391" alt="Screenshot 2021-11-06 at 17 54 49" src="https://user-images.githubusercontent.com/4855895/140619205-245cafc6-1d12-4de9-bb54-36adb63d3994.png">

If I enter my correct email address for my account, I receive a different message:

"We have emailed your password reset link!"

With OWASP security recommendations ideally the same message should be shown neither confirming or denying the validity of the email, something like "If the email you specified exists in our system, we've sent a password reset link to it."

**Comment by xlcrr** [comment]
This is a good point and it was raised with me recently. Will fix this now, thanks for pointing this out

**Comment by xlcrr** [comment]
fixed by https://github.com/OpenLitterMap/openlittermap-web/pull/372
