### ISSUE TITLE
In Mobile View, Render Points on Global Map

### ISSUE THREAD

**Issue by xlcrr** [OpenLitterMap/openlittermap-web#416]
When viewing the global map on a mobile device, the points do not show automatically

The user has to toggle the categories selection in the top-right to make the points show

**Comment by dassudip2001** [comment]
can i work this issue?

**Comment by xlcrr** [comment]
Hey @dassudip2001 it turns out this issue has resolved itself with an iOS update! Thanks for your interest, lots more issues to fix too
