### ISSUE TITLE
Names not shown on pictures on the Global Map

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#55]
The feature of showing names wherever possible is a cool one (it is a kind of compliment to the people who has done all the litterpicking),
and according to the setting-page your name will show on different places, like on top of the picture in the maps.
However, they are not shown at every picture. (probably none of them) in the Global Map.
For instance if i click on the picture in the netherlands, near Krommenie,
I can find my own picture that was taken of August 26, 2020, (a redbull-can).
This information is also shown in the picture, but it is not mentioning who took the picture.
(in the settings it does say 'Maps: credit my username' and my username is filled with a name, so it should be possible to show it.

**Comment by xlcrr** [comment]
This works on the city level map, but not yet the global map. We will get it done soon!

**Comment by xlcrr** [comment]
Merged by https://github.com/OpenLitterMap/openlittermap-web/pull/247
