### ISSUE TITLE
App: possible to chose a tag twice

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#56]
Open the OLM-app,
Select a photo to upload and choose 'done',
Type in the textfield 'face' and 'sanitary - facemask' appears.
select this tag.
Tap on the picture so the input-field disappears,
At this moment you see the picture, with 1 tag: 'Facemask (1)'. This is okay.

Now, tap on '+ add tag'.

The result:
The picture with 2 tags:
'Facemask (1)' and another one: 'Facemask (1).

Normally when you tap 'Add tag', the number increases (and indeed, after tapping 'Add tag' once more, the tag on the right changes to 'Facemask (2)'. This should have happened in the first case.

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
done
