### ISSUE TITLE
App: improvement, be able to use the previously given tags in another picture

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#57]
I have uploaded several pictures.
I tagged the first one and 'Confirm'.
The next picture appears with (and this is cool) the tags from the previous picture.
This is very helpful if the next picture is a similar item.
However, if you pick a lot of litter, the next picture is most likely to be something else.

What i think to be a handy way, is to choose the 'x', so you appear at the screen with all updated pictures.
I select one of the similar items and this one appears.
However, that last given tags are not shown anymore.
This is a shame.
Could be a nice improvement.

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
Done
