### ISSUE TITLE
How to Downloade Data set

### ISSUE THREAD

**Issue by aliman80** [OpenLitterMap/openlittermap-web#574]
Hi, First of all great work and excellent job done. I am trying to use this dataset for classification problem so i need to download this dataset but i cannot find where to download this dataset.  I have checked the website and also on the git hub but found no dataset. Can you help resolve this issue please?

**Comment by xlcrr** [comment]
Hi @aliman80 you can download the data by going to `World Cup` -> scroll down to the list of countries -> find the country you want -> Notice the tabs, select the `Download` one and enter your email

OpenLitterMap is in development, the images and OpenLitterAI is not ready yet

**Comment by YadneshD** [comment]
@xlcrr I need to download the raw images or annotations if they are available. How can I download them ? The CSV file does'nt has any links of the waste images.

**Comment by xlcrr** [comment]
Hi @YadneshD if you want the images please support the kickstarter in 2017 or the gofundme in 2020, thanks

https://gofundme.com/openlittermap

**Comment by YadneshD** [comment]
If someone needs to pay or fund it for getting the images, then why it is presented as open source? It is not a open source project.

**Comment by xlcrr** [comment]
It is open source. Its also in development. If you want it developed, maybe people who care about the environment should try and support it
