### ISSUE TITLE
App: After going back to select an extra picture, the previous selected pictures are gone

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#58]
Select some pictures to upload and choose 'Done'.
The next screen appears with these 3 pictures to tag.
Tag the first one and confirm
The next picture to tag appears.
Select 'x'.
The screen with the pictures appears (1 of them has a paperclip).
This is all okay.

Now select 'Photos' and select an extra picture and choose Done.
The result: this picture appears, all the other pictures, including the tagged one, are gone...

**Comment by xlcrr** [comment]
We will add these issues to the Mobile app repo when it goes open source, very soon ;-)

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
Done
