### ISSUE TITLE
App: Right tag not found in tag-searchfield

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#60]
go to the app,
I select 3 pictures, the first one is plastic so i use the textfield (really nice feature!), and type 'plastic'. 6 results are given, but none of them applies to the item that i am looking at. However, it really is plastic so i have to choose 1 of them...
However, i am 100% sure that there is also a tag with the name 'unidentified plastic' that is not in this list of 6.

Bug: if I remove the text that I entered, and start with 'unidenti', I get the missing option: 'unidentified plastic'. There seems to be a limit in the tags that are shown. There shouldn't be a limit.
If people don't know what tags are really available and search on 'plastic', they should get all tags containing 'plastic'.

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
Done
