### ISSUE TITLE
App: tags not in alphabetical order

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#61]
In some lists, the tags are not in alfabetical order, so if you are scrolling through the list just to see if a tag exists, you really have to scroll through the entire list.
If you know you are looking for a tag and you are sure it should be in the list, you will probably find it,
But if you are just looking for a tag that you are not sure exists in the list, this is not a desired way.
Make all lists in alphabetical order.

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
Done
