### ISSUE TITLE
App: remove the text after the tag has been chosen

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#62]
Go to the app,
use the textfield to search for a tag.
Chose it and confirm it.

Bug: the text that you entered in the textfield remains. 
So you have to delete it yourself to be able to type a 2nd tag.

Solution: after choosing confirm, remove the text that is entered in the textfield so you can immediately start with the next tag.

**Comment by xlcrr** [comment]
We will add mobile app issues to the mobile app repo when it launches. I will leave these open until then

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
Done
