### ISSUE TITLE
Map is broken on create cleanup

### ISSUE THREAD

**Issue by louisdvs** [OpenLitterMap/openlittermap-web#646]
Hey, 

I just created an account and wanted to set up a clean up, but the map click handler seems to be broken.

I tried 
- long click
- right click
- clicking at different zoom levels.

![Mar-13-2024 11-07-07](https://github.com/OpenLitterMap/openlittermap-web/assets/24875769/29953a03-0276-44e6-a384-3c5e85b8fb21)

Tested on chrome/firefox and also on my phone (with desktop view).

I'm happy to pull down the repo and have a look at fixing it if anyone has pointers on where to look? (I've worked with map box in the past)

Cheers

**Comment by xlcrr** [comment]
Thanks @louisdvs for the bug report just getting around to this now, will try to clear the issue and PR backlog soon

**Comment by xlcrr** [comment]
Thanks for reporting this @louisdvs fixed here https://github.com/OpenLitterMap/openlittermap-web/commit/6573b57b48cd4b19219e413ed3ded707f3c541fc
