### ISSUE TITLE
App: not clear what the switch is meant for

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#65]
If you are tagging a picture on the phone, in the right bottom, there is a switch. It is 'on', but it is not clear what it is meant for (no text, just a switch).
If you turn it off, it says 'the litter is still there'. I think that means that if it is set to 'on', the litter has been picked? Design-issue.

**Comment by xlcrr** [comment]
@FredMark Can you move this to [github.com/openlittermap/react-native](github.com/openlittermap/react-native)?

**Comment by FredMark** [comment]
Done
