### ISSUE TITLE
Tag-searchfield also needed in web

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#68]
in the app there is a textfield that i can use (i can type 'energ' to get the tag 'energy can'. In web this feature is not available, 
we really need this feature in web!!!

**Comment by xlcrr** [comment]
For categories + items, we should use [Vue-simple-suggest](https://github.com/KazanExpress/vue-simple-suggest)

**Comment by GeniJaho** [comment]
@FredMark @xlcrr is this about implementing a single search field both for categories and tags?

**Comment by FredMark** [comment]
Hi @GeniJaho ,

An example,
I have uploaded a balloon, or some metal object.
Now i am in the tag-screen and i want to tag the balloon.
If i am a new user (or if i have never uploaded a balloon before), i need to select a category first to see the different tags that belong under that category.
Well, probably not under 'smoking', so i look for another category that might have 'balloon'.
This is taking a lot of effort.
What i am looking for, is a searchfield where i can type 'balloon' and the tag appears so i can choose it (or maybe even several results if, for instance, i type 'plastic' and plastic is found in different tags.
So the way becomes more logical, i don't want to be forced to decide under which category it lives, i only know that i found a balloon and want to be able to select that tag.

Another example, i found a pair of glasses.
I have to open each category and look at all available tags to see if they are under one of these categories.
After having looked at the last one, i think there is no tag 'glasses', 
I would have know this instantly if i could use a text-search, and typed 'glass' (i would find some glass-bottles maybe, or 'broken glass', but no 'glasses'.
