### ISSUE TITLE
Global map - disable pan when mouse moves while zooming 

### ISSUE THREAD

**Issue by xlcrr** [OpenLitterMap/openlittermap-web#72]
If you are scrolling in or out using the new zoom feature, the map will pan if the mouse moves

We want to allow the user the move their mouse but it should not pan the map

**Comment by willalexander** [comment]
I think we can fix this by removing line 59 of resources/js/views/global/SmoothWheelZoom.js:

`this._wheelMousePosition = this._map.mouseEventToContainerPoint(e);`

This line is updating the zoom's centre point throughout the zoom movement.

**Comment by xlcrr** [comment]
Fixed https://github.com/OpenLitterMap/openlittermap-web/pull/134
