### ISSUE TITLE
Set of issues in tags on web

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#92]
In web you have different categories with tags in them to choose from.
Below a list of bugs in these lists:

There are different categories:
[v] the order of these categories is correct, but 'Other' should be the last option

Alcohol:
[v] the order of the tags not correct, set in alphabetical order and let 'Alcohol-Other' be the last one

Art:
- It is a tag that you can choose in the app, so it should also be available in web: item
(it is the only tag in the category, and the category itself does exists, but the tag is not shown. other tags from another category are shown, probably because this tag 'item' does not exist.

Brands: --> PR created 1/3/2021 (changes in js/extra/litterkeys.js, langs/en/litter.json and langs/nl/litter.json
[v] It is a tag that you can choose in the app, so it should also be available in web: aldi
[v] It is a tag that you can choose in the app, so it should also be available in web: applegreen 
[v] It is a tag that you can choose in the app, so it should also be available in web: asahi
[v] It is a tag that you can choose in the app, so it should also be available in web: avoca
[v] It is a tag that you can choose in the app, so it should also be available in web: ballygowan
[v] It is a tag that you can choose in the app, so it should also be available in web: bewleys
[v] It is a tag that you can choose in the app, so it should also be available in web: brambles
[v] It is a tag that you can choose in the app, so it should also be available in web: bulmers
[v] It is a tag that you can choose in the app, so it should also be available in web: burgerking
[v] It is a tag that you can choose in the app, so it should also be available in web: butlers
[v] It is a tag that you can choose in the app, so it should also be available in web: cadburys
[v] It is a tag that you can choose in the app, so it should also be available in web: cafe nero
[v] It is a tag that you can choose in the app, so it should also be available in web: carlsberg
[v] It is a tag that you can choose in the app, so it should also be available in web: centra
[v] It is a tag that you can choose in the app, so it should also be available in web: circlek
[v] It is a tag that you can choose in the app, so it should also be available in web: coles
[v] It is a tag that you can choose in the app, so it should also be available in web: evian
[v] It is a tag that you can choose in the app, so it should also be available in web: fosters
[v] It is a tag that you can choose in the app, so it should also be available in web: guinness
[v] It is a tag that you can choose in the app, so it should also be available in web: nero
[v] It is a tag that you can choose in the app, so it should also be available in web: mars
[v] the tag 'kellogs' is not working correctly (translation-thing?). At this moment it is shown as 'litter.brands.kellogs'
[v] the tag 'lego' is not working correctly (translation-thing?). At this moment it is shown as 'litter.brands.lego'

Coastal
[v] the order of the tags not correct, set in alphabetical order and let 'Coastal-Other' be the last one

Food:
[v] the order of the tags not correct, set in alphabetical order and let 'Food-Other' be the last one
[v] 'Pizza Box' missing as a tag. (it is a tag that you can choose in the app, so it should be in web as well)
- (bug in web: cardboard-food-packaging is a column in the excel, but you can not choose it in web under FOOD)

Industrial: 
[v] the order of the tags not correct, set in alphabetical order and let 'Industrial-Other' be the last one

Sanitary:
[v] the order of the tags not correct, set in alphabetical order and let 'Sanitary-Other' be the last one

Smoking:
[v] the order of the tags not correct, set in alphabetical order and let 'Smoking-Other' be the last one

Softdrinks:
[v] the order of the tags not correct, set in alphabetical order and let 'Softdrink-Other' be the last one

Other:
[v] the order of the tags not correct, set in alphabetical order and let 'Other-Other' be the last one
[v] 'pet surprise' is ambiguous, in the excel-export the column is named 'dogshit'. Use this name also in web as the tag. (or 'dog poo' if 'shit' is too bold.
[v] 'bags of litter' missing as a tag. (it is a tag that you can choose in the app, so it should be in web as well)
[v] 'surprise in a bag' is ambiguous, call it 'dogshit in a bag' (or 'dog poo in a bag' if 'shit' is too bold
[v] 'Overflowing bins' missing as a tag. (it is a tag that you can choose in the app, so it should be in web as well)
[v] 'Tyre' missing as a tag. (it is a tag that you can choose in the app, so it should be in web as well)
[v] 'Cable tie' missing as a tag. (it is a tag that you can choose in the app, so it should be in web as well)
[v] 'Balloons' missing as a tag. (it is a tag that you can choose in the app, so it should be in web as well)

**Comment by xlcrr** [comment]
Thanks for the issue

The order of the tags is set by popularity, not A-Z.

However, we can give users to order the tags however they want. A-Z for whatever language they are using, or by community popularity, their own popularity, or whatever order they would prefer.

We might also want to load different brands for each country depending on what country the user is uploading from.

**Comment by FredMark** [comment]
"However, we can give users the ability to order the tags however they want",
That would be perfect, i think.
having it set by popularity doesn't help me much.
If 'the community' is picking a lot of cigarettebutts, then this order is helping them, but not helping somebody that is picking plastic nurdles most of the time and never picking butts.
And if i am switching from picking cans to picking plastic bottles most of the time, it could be very helpful to be able to put plastic bottles as the first possible tag for a while.
At this moment de popularity-order is probably a result of a few users.
But all new users won't understand this order and will probably have to search a lot because the order is 'random' at this moment. Probably best to start with an alfabatical order until it is possible to arrange the order yourself (as a user).

**Comment by FredMark** [comment]
Most bugs out of this collection of bugs are solved by now.
I am closing it and create seperate issues for those bugs that still exist so they can be handled by different people whenever there is time.
