### ISSUE TITLE
Set of issues in Export to CSV

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#93]
In web, you can give tags to an item.
These given tags should be shown in the export that you can make.
However, some tags are not shown so i checked all possible tags that you can give in web and checked the export that resulted from it, below are the bugs.
Bugs with [ ] still need to be solved, bugs with [/] are the ones that could be solved with the latest fix, but still need testing, bugs with [v] have been tested and are solved at this moment.

Tags regarding Smoking:
[v] the name of the column is not conform the tag that you can give in web/app: It is Papers_filters, but should be Rolling Papers
[v] the name of the column is 'plastic_smoking_pk', this should be plastic_smoking_packaging (nobody knows what 'pk' is).
[v] the next tag that can be given in web/app is missing in the export: Vape Pen
[v] the next tag that can be given in web/app is missing in the export: Vape Oil

Tags regarding Food:
In web and app there is 1 combined tag that you can choose: 'paper/cardboard packaging'. This tag can be found in the export under the column 'paperFoodPackaging'. However, in the export there is also a column 'cardboardFoodPackaging'. This tag can not be chosen in app/web and will always be 0 and is thus obsolete:
[v] rename the column of the one that is always be used (paperFoodPackaging := paperCardbordFoodPackaging
[v] the next tag that can be given in web/app is missing in the export: Pizza Box
[v] the next tag that can be given in web/app is missing in the export: Aluminium Foil

Tags regarding Alcohol:
[v] in web and app there is a tag 'beer bottle tops'. However, the excel-export column is 'bottleTops'. Because of this name, it is not clear that these bottletops are beer bottle tops. Change it to 'beer_bottle_tops'
[v] the next tag that can be given in web/app is missing in the export: Six-pack rings
[v] the next tag that can be given in web/app is missing in the export: Plastic cups
[v] the next tag that can be given in web/app is missing in the export: Pint glass

Tags regarding Softdrinks:
[v] in web and app there is a tag 'plastic fizzy drink bottle'. However, the excel-export column is 'fizzyDrinkBottle'. Because of this name, it is not clear that these drink bottles are plastic drink bottles. Change it to 'plastic_fizzy_drink_bottles'
[v] in web and app there is a tag 'bottle tops'. However, the excel-export column is 'bottlelid'. Because of this name, it is not clear that these 'lids' were actually tops. Change it to 'softdrink bottle tops'. (Beware: start with softdrink, because there is also a column with 'beer bottle tops', so this is the way to make the distinction between them)
[v] the next tag that can be given in web/app is missing in the export: Pull ring
[v] the next tag that can be given in web/app is missing in the export: Straw packaging
[v] the next tag that can be given in web/app is missing in the export: Styrofoam cup
[v] If you tag a picture with Softdrinks > plastic-water-bottle, it wil not show-up in the excel, see litter_id=112853 (did show on the photo)

Tags regarding Sanitary:
[v] the next tag that can be given in web/app is missing in the export: Wet wipes
[v] the next tag that can be given in web/app is missing in the export: Nappies
[v] the next tag that can be given in web/app: menstral. However, in the export this is called 'mental'

Tags regarding Other:
[v] in web/app there is a tag 'Random Litter'. However, in the export this is called 'random dump'. Change it to 'random litter'
[v] the next tag that can be given in web/app is missing in the export: Bags of litter
[v] the next tag that can be given in web/app is missing in the export: Dogshit in a bag (dog poo in a bag)
[v] the next tag that can be given in web/app is missing in the export: Automobile
[v] the next tag that can be given in web/app is missing in the export: Clothing
[v] the next tag that can be given in web/app is missing in the export: Traffic cone
[v] the next tag that can be given in web/app is missing in the export: Life buoy
[v] in web/app there is a tag 'Unidentified plastic'. However, in the export this is called 'no id plastic'. Change it to 'unidentified plastic'
[v] the next tag that can be given in web/app is missing in the export: Overflowing bins
[v] the next tag that can be given in web/app is missing in the export: Tyre
[v] the next tag that can be given in web/app is missing in the export: Cable tie
[v] the next tag that can be given in web/app is missing in the export: Balloons
[v] in web/app there is a tag 'ear plugs (music)'. However, in the export this is called 'ear plugs'. Change it to 'ear plugs (music)'
[v] in web/app there is a tag 'Other_other'. However, in the export this is called 'other_unknown'. Change it to 'Other_Other'

Tags regarding Coastal:
[v] the next tag that can be given in web/app is missing in the export: Styrofoam S
[v] the next tag that can be given in web/app is missing in the export: Styrofoam M
[v] the next tag that can be given in web/app is missing in the export: Styrofoam L
[v] in web/app there is a tag 'balloons'. However, in the export this is called 'baloons'. Change it to 'balloons'

Tags regarding Brands:
[v] the comment-line 'brands' is missing in the .php-file
[v] in web/app there is a tag 'coca cola'. However, in the export this is called 'coke'. Change it to 'coca cola'
[v] the next tag that can be given in web/app is missing in the export: Evian
[v] the next tag that can be given in web/app is missing in the export: Fosters
[v] the next tag that can be given in web/app is missing in the export: Stella

Tags regarding Industrial:
[v] in web/app you can choose the category 'industrial' with some different possible tags, none of them are in the export:
[v] the next tag that can be given in web/app is missing in the export: Oil
[v] the next tag that can be given in web/app is missing in the export: Chemical
[v] the next tag that can be given in web/app is missing in the export: Plastic
[v] the next tag that can be given in web/app is missing in the export: Bricks
[v] the next tag that can be given in web/app is missing in the export: Tape
[v] the next tag that can be given in web/app is missing in the export: Other

Tags regarding Dumping:
[v] in web/app you can choose the category 'dumping' with some different possible tags, none of them are in the export:
[v] the next tag that can be given in web/app is missing in the export: dumping small
[v] the next tag that can be given in web/app is missing in the export: dumping medium
[v] the next tag that can be given in web/app is missing in the export: dumping large

General issue:
[v] in the export there are column-names like "name_name", but there are also names like "nameName". Choose one way and keep them all alike
[v] headers of the excel: all in singular

[v] it would help to insert and empty column with the name of the category. (so 'Coastal' as a column name, followed by the different columns that fall under coastal.

Tags regarding Other:
[v] the next tag that can be given in web/app is missing in the export: Illegal dumping (Still open because i can not find the name of this 'illegal dumping' column in the 'other'-table

[v] If you tag a picture with Alcohol > Plastic-cup, it wil not show-up in the excel, see litter_id=112845 (did show on the photo)

[v] If you tag a picture with Industrial > Plastic, it wil not show-up in the excel, see litter_id=112850 (also not shown on the photo)
[v] If you tag a picture with Industrial > Other, it wil not show-up in the excel, see litter_id=112850 (also not shown on the photo)

[v] If you tag a picture with Other > Unidentified-plastic, it wil not show-up in the excel, see litter_id=112851 (did show on the photo)
[v] If you tag a picture with Other > illegal-dumping, it wil not show-up in the excel, see litter_id=112851 (did show on the photo)
[v] If you tag a picture with Other > Metal-object, it wil not show-up in the excel, see litter_id=112851 (did show on the photo)
[v] If you tag a picture with Other > Magazines, it wil not show-up in the excel, see litter_id=112851 (did NOT show on the photo)
[v] If you tag a picture with Other > Random-litter, it wil not show-up in the excel, see litter_id=112851 (did show on the photo)

Issues still open:
 
Tags regarding Art:
[ ] in web/app you can choose the category 'art' with 1 possible tag, this doesn't exist in the export:
[ ] the next tag that can be given in web/app is missing in the export: art item

Tags regarding Food:
[ ] remove everything that involves cardboardFoodPackaging (or keep it and make sure that this can also be chosen in app/web)

[ ] After committing a lot of fixes on the createcsv, there still are a lot of items that have 'total_litter = 0'.

General issues:
[ ] it could be helpful to sort the columns per category (but beware, if the tags are something with 'small/medium/large', then keep them in the order 's/m/l')

**Comment by xlcrr** [comment]
Thanks for the issue.

We use the same name in the column in Excel that we use in the database tables.

Happy to change this if users would prefer to see something else in the column header

**Comment by FredMark** [comment]
I've taken a look at the code, but if i understand it correctly, we use the name of the database-column to do the counting, but the names in the columns are free to choose (there are already examples of columnnames that seem to be different than the names in the database.

I have make a lot of changes and i think this should be much better now.
See slack for extra info.

**Comment by xlcrr** [comment]
We should use the translated strings for the column names

**Comment by FredMark** [comment]
I agree, but first let me fix (and finish) the download so that every tag that is chosen while tagging the litter is also presented in the download.
If that is working, the next step is probably refactoring.
Apart from the translation, i think we also need to look at the categories/tags themselves (can we come up with a tree where there is little to no item in the 'Other-category').
