### ISSUE TITLE
Chosen language is set to English again after logging in

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#95]
If you go to openlittermap.com and change the language to another language (in this case i have set it to Dutch),
and if you then login,
you are forwarded to the upload page,
if you go back to (for instance) the 'about page', it is shown in English again.

**Comment by xlcrr** [comment]
Thanks for the report,

I am aware of this, it will be fixed tonight

**Comment by xlcrr** [comment]
Fixed
